name: Create Pre-Release On Merge (app)

on:
  push:
    branches:
      - dev
    paths:
      - app
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'gradle'

      - run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build assembleDebug

      - run: mv app/build/outputs/apk/debug/*.apk Blocktopograph.apk
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: nigtly
          name: "Per"
          artifacts: "Blocktopograph.apk"
          allowUpdates: true
