name: Create Pre-Release On Merge (app)

on:
  push:
    branches:
      - release
    paths:
      - app/src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'gradle'

      - run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Create Debug APK
        run: ./gradlew assembleDebug
                    
      # Publish APK
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ github.event.inputs.region }}-v${{ env.PERSEUS_VERSION }}"
          name: "Release"
          artifacts: "build/*.apk"
          allowUpdates: true
